# Generated by Django 5.1.4 on 2025-07-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('organization_name', models.CharField(choices=[('GRI Standards', 'GRI Standards'), ('TCFD', 'TCFD (Task Force on Climate-related Financial Disclosures)'), ('SASB', 'SASB (Sustainability Accounting Standards Board)'), ('King IV', 'King IV (South Africa)'), ('CDP', 'CDP (Carbon Disclosure Project)'), ('UNGC', 'UNGC (United Nations Global Compact)')], max_length=100)),
                ('reporting_year', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025)),
                ('report_type', models.CharField(choices=[('Annual', 'Annual Report'), ('Quarterly', 'Quarterly Report'), ('Interim', 'Interim Report')], max_length=50)),
                ('document_version', models.CharField(blank=True, max_length=50)),
                ('report_sector', models.CharField(choices=[('Energy', 'Energy'), ('Manufacturing', 'Manufacturing'), ('Technology', 'Technology'), ('Financial Services', 'Financial Services'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Consumer Goods', 'Consumer Goods'), ('Real Estate', 'Real Estate')], max_length=100)),
                ('compliance_frameworks', models.TextField()),
                ('geographical_region', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=50)),
                ('report_description', models.TextField(blank=True)),
                ('report_file', models.FileField(upload_to='esg_reports/')),
                ('document_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESGComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_area', models.CharField(max_length=255)),
                ('disclosure_title', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='compliance.esgcompliancereport')),
            ],
        ),
    ]
