# Generated by Django 5.1.2 on 2025-07-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='esg_reports/')),
                ('document_title', models.CharField(max_length=255)),
                ('industry_sector', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=255)),
                ('country_region', models.CharField(max_length=100)),
                ('reporting_year', models.PositiveIntegerField()),
                ('reporting_period', models.CharField(max_length=100)),
                ('standards_applied', models.CharField(max_length=500)),
                ('report_type', models.CharField(max_length=100)),
                ('is_peer_report', models.BooleanField(default=False)),
                ('peer_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.esgcompany')),
            ],
        ),
    ]
