# Generated by Django 5.1.2 on 2025-07-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgcomplianceframework',
            name='sub_standard_area',
            field=models.TextField(blank=True),
        ),
    ]
