# Generated by Django 5.1.2 on 2025-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_esgreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgreport',
            name='country_region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=50),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='industry_sector',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Financials', 'Financial Services'), ('Healthcare', 'Healthcare'), ('Consumer Goods', 'Consumer Goods'), ('Technology', 'Technology'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Utilities', 'Utilities'), ('Consumer Services', 'Consumer Services'), ('Real Estate', 'Real Estate'), ('Telecommunication Services', 'Telecommunications'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Basic Materials', 'Basic Materials'), ('Transportation', 'Transportation'), ('Healthcare Services', 'Healthcare Services'), ('Leisure & Luxury Goods', 'Leisure & Luxury Goods'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Renewables', 'Renewables'), ('Chemicals', 'Chemicals'), ('Mining', 'Mining'), ('Forestry & Paper', 'Forestry & Paper'), ('Agriculture', 'Agriculture'), ('Construction & Engineering', 'Construction & Engineering')], max_length=255),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='organization_type',
            field=models.CharField(choices=[('Public Company', 'Public Company'), ('Private Company', 'Private Company'), ('Government Entity', 'Government Entity'), ('Non-Profit', 'Non-Profit'), ('Financial Institution', 'Financial Institution'), ('State-Owned Enterprise', 'State-Owned Enterprise'), ('Multinational Corporation', 'Multinational Corporation'), ('Startup', 'Startup'), ('SME', 'Small & Medium Enterprise'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='report_type',
            field=models.CharField(choices=[('Sustainability', 'Sustainability Report'), ('Integrated', 'Integrated Report'), ('Climate', 'Climate Report'), ('Annual', 'Annual Report'), ('Financial and ESG', 'Financial and ESG Report'), ('Other', 'Other')], default='Annual', max_length=100),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='reporting_period',
            field=models.CharField(choices=[('Annual', 'Annual Report'), ('Quarterly', 'Quarterly Report'), ('Periodic', 'Periodic Updates')], max_length=100),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='reporting_year',
            field=models.PositiveIntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025),
        ),
        migrations.AlterField(
            model_name='esgreport',
            name='standards_applied',
            field=models.TextField(),
        ),
    ]
