# Generated by Django 5.1.2 on 2025-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_esgcomplianceframework_sub_standard_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcomplianceframework',
            name='sub_standard_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
