# Generated by Django 5.1.4 on 2025-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='compliance_frameworks',
            field=models.TextField(),
        ),
    ]
