# Generated by Django 5.1.2 on 2025-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_esgcomplianceframework_sub_standard_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcomplianceframework',
            name='disclosure_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esgcomplianceframework',
            name='recommendations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='esgcomplianceframework',
            name='standard_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esgcomplianceframework',
            name='sub_standard_area',
            field=models.TextField(),
        ),
    ]
