# Generated by Django 5.1.4 on 2025-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_esgcompliancereport_compliance_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='geographical_region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], default='Not Necessary', max_length=50),
        ),
    ]
