# Generated by Django 5.1.2 on 2025-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_esgreport_country_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgreport',
            name='reporting_year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025),
        ),
    ]
