# Generated by Django 5.1.2 on 2025-07-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_esgcompliancesummary_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGComplianceFrameworkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_area', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_standard_area', models.TextField()),
                ('disclosure_title', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField()),
                ('recommendations', models.TextField()),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures_test', to='compliance.esgcompliancereport')),
            ],
        ),
    ]
