# Generated by Django 5.1.4 on 2025-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alter_esgcompliancereport_geographical_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website_url', models.URLField()),
                ('esg_compliant', models.BooleanField(default=False)),
            ],
        ),
    ]
