# Generated by Django 5.1.4 on 2025-07-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_esgcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='organization_name',
            field=models.CharField(choices=[('GRI Standards', 'GRI Standards'), ('TCFD', 'TCFD (Task Force on Climate-related Financial Disclosures)'), ('SASB', 'SASB (Sustainability Accounting Standards Board)'), ('King IV', 'King IV (South Africa)'), ('CDP', 'CDP (Carbon Disclosure Project)'), ('UNGC', 'UNGC (United Nations Global Compact)'), ('ISO', 'ISO (International Organization for Standardization)'), ('OECD', 'OECD Guidelines for Multinational Enterprises'), ('PRI', 'PRI (Principles for Responsible Investment)'), ('FSC', 'FSC (Forest Stewardship Council)'), ('Fairtrade', 'Fairtrade'), ('SARB', 'South African Reserve Bank (SARB)'), ('EU', 'European Union (EU)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='report_sector',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Financials', 'Financial Services'), ('Healthcare', 'Healthcare'), ('Consumer Goods', 'Consumer Goods'), ('Technology', 'Technology'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Utilities', 'Utilities'), ('Consumer Services', 'Consumer Services'), ('Real Estate', 'Real Estate'), ('Telecommunication Services', 'Telecommunications'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Basic Materials', 'Basic Materials'), ('Transportation', 'Transportation'), ('Financial Services', 'Financial Services'), ('Healthcare Services', 'Healthcare Services'), ('Leisure & Luxury Goods', 'Leisure & Luxury Goods'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Renewables', 'Renewables'), ('Chemicals', 'Chemicals'), ('Mining', 'Mining'), ('Forestry & Paper', 'Forestry & Paper'), ('Agriculture', 'Agriculture'), ('Construction & Engineering', 'Construction & Engineering')], max_length=100),
        ),
    ]
