# Generated by Django 5.1.2 on 2025-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_esgcomplianceframeworktest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcomplianceframeworktest',
            name='sub_standard_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
