# Generated by Django 5.1.2 on 2025-07-14 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_esgreport_industry_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_sector', models.CharField(choices=[('Energy', 'Energy'), ('Financials', 'Financial Services'), ('Healthcare', 'Healthcare'), ('Consumer Goods', 'Consumer Goods'), ('Technology', 'Technology'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Utilities', 'Utilities'), ('Consumer Services', 'Consumer Services'), ('Real Estate', 'Real Estate'), ('Telecommunication Services', 'Telecommunications'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Basic Materials', 'Basic Materials'), ('Transportation', 'Transportation'), ('Healthcare Services', 'Healthcare Services'), ('Leisure & Luxury Goods', 'Leisure & Luxury Goods'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Renewables', 'Renewables'), ('Chemicals', 'Chemicals'), ('Mining', 'Mining'), ('Forestry & Paper', 'Forestry & Paper'), ('Agriculture', 'Agriculture'), ('Construction & Engineering', 'Construction & Engineering')], max_length=255)),
                ('country_region', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=50)),
                ('organization_type', models.CharField(choices=[('Public Company', 'Public Company'), ('Private Company', 'Private Company'), ('Government Entity', 'Government Entity'), ('Non-Profit', 'Non-Profit'), ('Financial Institution', 'Financial Institution'), ('State-Owned Enterprise', 'State-Owned Enterprise'), ('Multinational Corporation', 'Multinational Corporation'), ('Startup', 'Startup'), ('SME', 'Small & Medium Enterprise'), ('Other', 'Other')], max_length=255)),
                ('peer_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.esgcompany')),
            ],
        ),
    ]
