# Generated by Django 5.1.2 on 2025-07-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_esgreportbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateBulkESGReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='corporate_reports/')),
                ('document_title', models.CharField(max_length=255)),
                ('reporting_year', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025)),
                ('reporting_period', models.CharField(choices=[('Annual', 'Annual Report'), ('Quarterly', 'Quarterly Report'), ('Periodic', 'Periodic Updates')], max_length=50)),
                ('standards_applied', models.TextField()),
                ('report_type', models.CharField(choices=[('Sustainability', 'Sustainability Report'), ('Integrated', 'Integrated Report'), ('Climate', 'Climate Report'), ('Annual', 'Annual Report'), ('Financial and ESG', 'Financial and ESG Report'), ('Other', 'Other')], default='Annual', max_length=50)),
                ('is_peer_report', models.BooleanField(default=False)),
                ('peer_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.esgreportbatch')),
            ],
            options={
                'unique_together': {('batch', 'document_title', 'reporting_year', 'report_type')},
            },
        ),
    ]
