# Generated by Django 5.1.4 on 2025-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_alter_esgcompliancereport_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='organization_name',
            field=models.CharField(choices=[('GRI', 'Global Reporting Initiative (GRI)'), ('SASB', 'Sustainability Accounting Standards Board (SASB)'), ('TCFD', 'Task Force on Climate-related Financial Disclosures (TCFD)'), ('IFRS', 'International Financial Reporting Standards (IFRS)'), ('EU', 'European Union (EU)'), ('SEC', 'Securities and Exchange Commission (SEC)'), ('SARB', 'South African Reserve Bank (SARB)'), ('PRB', 'Principles for Responsible Banking (PRB)'), ('ISO', 'International Organization for Standardization (ISO)'), ('Fairtrade', 'Fairtrade'), ('FSC', 'Forest Stewardship Council (FSC)'), ('UNGC', 'United Nations Global Compact (UNGC)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='report_sector',
            field=models.TextField(),
        ),
    ]
