# Generated by Django 5.1.2 on 2025-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_alter_esgcomplianceframeworktest_sub_standard_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgcompliancescore',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esgcompliancescore',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
