# Generated by Django 5.1.2 on 2025-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_corporatebulkesgreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatebulkesgreports',
            name='document_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
