# Generated by Django 5.1.4 on 2025-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_alter_esgcompliancereport_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='organization_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='esgcompliancereport',
            name='report_type',
            field=models.CharField(choices=[('Annual', 'Annual Report'), ('Quarterly', 'Quarterly Report'), ('Periodic', 'Periodic Updates')], max_length=50),
        ),
    ]
